/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6WN1BM6ZKph
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link'
import { Drawer, DrawerTrigger, DrawerContent } from '@/components/ui/drawer'
import { Button } from '@/components/ui/button'

export function Navbar() {
  return (
    <header className="flex h-16 w-full items-center justify-between bg-background px-4 md:px-6">
      <Link href="#" className="flex items-center gap-2" prefetch={false}>
        <MountainIcon className="h-6 w-6" />
        <span className="text-lg font-semibold">Acme Inc</span>
      </Link>
      <nav className="hidden items-center gap-6 md:flex">
        <Link
          href="/"
          className="text-sm font-medium transition-colors hover:text-primary"
          prefetch={false}
        >
          Home
        </Link>
        {/* <Link href="#" className="text-sm font-medium transition-colors hover:text-primary" prefetch={false}>
          About
        </Link>
        <Link href="#" className="text-sm font-medium transition-colors hover:text-primary" prefetch={false}>
          Services
        </Link>
        <Link href="#" className="text-sm font-medium transition-colors hover:text-primary" prefetch={false}>
          Contact
        </Link> */}
      </nav>
      <Drawer>
        <DrawerTrigger asChild>
          <Button variant="outline" size="icon" className="md:hidden">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation</span>
          </Button>
        </DrawerTrigger>
        <DrawerContent side="left">
          <div className="flex flex-col items-start gap-6 p-6">
            <Link
              href="/"
              className="text-lg font-medium transition-colors hover:text-primary"
              prefetch={false}
            >
              Home
            </Link>
            {/* <Link href="#" className="text-lg font-medium transition-colors hover:text-primary" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-lg font-medium transition-colors hover:text-primary" prefetch={false}>
              Services
            </Link>
            <Link href="#" className="text-lg font-medium transition-colors hover:text-primary" prefetch={false}>
              Contact
            </Link> */}
          </div>
        </DrawerContent>
      </Drawer>
    </header>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
